pipeline {
    agent {
        kubernetes {
            inheritFrom 'docker-arm'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    parameters {
        string(name: 'TAG_NAME', defaultValue: '', description: 'The release version number.')
    }

    stages {
        stage('Prepare') {
            steps {
                script {
                    currentBuild.displayName = "#${BUILD_NUMBER}:${TAG_NAME}"
                }
            }
        }

        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "refs/tags/${TAG_NAME}"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'docker-inbound-agent']],
                    userRemoteConfigs: [[url: 'https://github.com/jenkinsci/docker-inbound-agent.git']]
                ])
            }
        }

        stage('Modify Dockerfile') {
            steps {
                dir('./docker-inbound-agent/11/debian') {
                    sh 'sed -i "s/jenkins\\/agent:$version/tenbriz\\/jenkins-agent:$version/" Dockerfile'
                }
            }
        }

        stage('Copy Agent') {
            steps {
                dir('./docker-inbound-agent') {
                    sh 'cp -f jenkins-agent 11/debian/'
                }
            }
        }

        stage('Build') {
            steps {
                container('docker') {
                    dir('./docker-inbound-agent/11/debian') {
                        sh "docker build -t tenbriz/jenkins-inbound-agent:latest -t tenbriz/jenkins-inbound-agent:${params.TAG_NAME}-jdk11 ."
                    }
                }
            }
        }

        stage('Push') {
            steps {
                container('docker') {
                    dir('./docker-inbound-agent/11/debian') {
                        withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'DOCKER_LOGIN_PASSWORD', usernameVariable: 'DOCKER_LOGIN_USERNAME')]) {
                            sh "docker login -u ${DOCKER_LOGIN_USERNAME} -p ${DOCKER_LOGIN_PASSWORD}"
                        }

                        sh "docker push tenbriz/jenkins-inbound-agent:${params.TAG_NAME}-jdk11"
                        sh "docker push tenbriz/jenkins-inbound-agent:latest"
                    }
                }
            }
        }
    }
}
