longhorn:
  ingress:
    enabled: true
    ingressClassName: nginx
    host: "longhorn.caas.i.kiessla.de"
    tls: "true"
    tlsSecret: "longhorn.acme-tls"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
