---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: intranet
spec:
  ipAddressPools:
    - intranet
  peers:
    - intranet
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: internet
spec:
  ipAddressPools:
    - internet
  peers:
    - internet
