---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: intranet
spec:
  ipAddressPools:
    - intranet
  peers:
    - intranet
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: internet
spec:
  ipAddressPools:
    - internet
  peers:
    - internet
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: app
spec:
  ipAddressPools:
    - app
  peers:
    - app
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: k0s-worker01
    - matchLabels:
        kubernetes.io/hostname: k0s-worker02
    - matchLabels:
        kubernetes.io/hostname: k0s-worker03
