---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: intranet
spec:
  myASN: 64550
  peerASN: 64500
  peerAddress: 10.0.50.1
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: internet
spec:
  myASN: 64540
  peerASN: 64500
  peerAddress: 10.0.40.1
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: app
spec:
  myASN: 64590
  peerASN: 64500
  peerAddress: 10.0.90.1
