service:
  enabled: false

metallb:
  controller:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

  speaker:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 100Mi