---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-secrets
  namespace: jenkins
data:
  LDAP_PASSWORD: {{ .Values.ldap.password | b64enc }}
  GITHUB_PASSWORD: {{ .Values.github.password | b64enc }}
  DOCKER_PASSWORD: {{ .Values.docker.password | b64enc }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: jenkins
data:
  .dockerconfigjson: {{ .Values.docker.configjson | b64enc }}
