# Values for the traefik sub-chart.
internal:
  deployment:
    replicas: 1

  # Use ingressClass. Ignored if Traefik version < 2.3 / kubernetes < 1.18.x
  ingressClass:
    enabled: true
    isDefaultClass: true

  # Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      enabled: false

  globalArguments:
    - "--global.checknewversion"

  # Options for the main traefik service, where the entrypoints traffic comes
  # from.
  service:
    spec:
      loadBalancerIP: 10.0.50.5

  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"

# Values for the traefik sub-chart.
external:
  deployment:
    replicas: 1

  # Use ingressClass. Ignored if Traefik version < 2.3 / kubernetes < 1.18.x
  ingressClass:
    enabled: true
    isDefaultClass: false

  # Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      enabled: false

  globalArguments:
    - "--global.checknewversion"

  # Options for the main traefik service, where the entrypoints traffic comes
  # from.
  service:
    spec:
      loadBalancerIP: 10.0.40.5

  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
