---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-authelia
  namespace: {{ .Release.Namespace }}
spec:
  numberOfInstances: 3
  postgresql:
    version: "14"
  teamId: "acid"
  volume:
    size: 1Gi
  preparedDatabases:
    authelia:
      defaultUsers: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
