unifi:
  env:
    TZ: "Europe/Berlin"

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: unifi.caas.i.kiessla.de
          paths:
            - path: /
              pathType: Prefix
              service:
                name: unifi
                port: 8443
      tls:
        - secretName: unifi.acme-tls
          hosts:
            - unifi.caas.i.kiessla.de

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
