---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-public
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx-public
  rules:
    - http:
        paths:
          {{- range .Values.http.publicPaths }}
          - backend:
              service:
                name: {{ $.Chart.Name }}-service
                port:
                  number: 8443
            path: {{ .path }}
            pathType: {{ .pathType }}
          {{- end }}
      host: {{ .Values.http.hostname.public }}
  tls:
    - secretName: {{ .Values.http.tlsSecretName }}
      hosts:
        - {{ .Values.http.hostname.public }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: 8443
            pathType: ImplementationSpecific
      host: {{ .Values.http.hostname.admin }}
  tls:
    - secretName: keycloak-admin.acme-tls
      hosts:
        - {{ .Values.http.hostname.admin }}
