---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  labels:
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
type: Opaque
data:
  access-token: {{ .Values.digitalocean.accessToken }}
