pipeline {
    agent {
        kubernetes {
            inheritFrom 'kaniko'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    parameters {
        string(name: 'TAG_NAME', defaultValue: 'v1.4.3', description: 'The release version number.')
    }

    stages {
        stage('Prepare') {
            steps {
                script {
                    currentBuild.displayName = "#${BUILD_NUMBER}:${params.TAG_NAME}"
                }
            }
        }

        stage('Checkout') {
            steps {
                checkout poll: false, scm: [
                    $class: 'GitSCM',
                    branches: [[name: "refs/tags/${params.TAG_NAME}"]],
                    userRemoteConfigs: [[url: 'https://github.com/ltb-project/self-service-password.git']]
                ]
            }
        }

        stage('Modify Dockerfile') {
            steps {
                sh "sed -i 's/x86_64/\$(uname -m)/g' ./Dockerfile"
            }
        }

        stage("Build & Push") {
            steps {
                container('kaniko') {
                    sh "/kaniko/executor --force --context=dir://./ -f ./Dockerfile --cache=true --destination=tenbriz/self-service-password:${params.TAG_NAME}"
                }
            }
        }
    }
}