openldap-stack-ha:

  # Override name of deployment.
  nameOverride: "openldap"
  fullnameOverride: "openldap"

  # Amount of pods to be used.
  replicaCount: 3

  # Update strategy for new rollouts.
  strategy: {}
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 1
#      maxSurge: 1

  # Overwrite default pullPolicy which is 'Always'.
  image:
    pullPolicy: IfNotPresent

  # Specifies an existing secret to be used for admin and config user passwords
  existingSecret: "openldap-secret"

  tls:
    enabled: false

  env:
    LDAP_LOG_LEVEL: "256"
    LDAP_ORGANISATION: "Kiessla HomeLab"
    LDAP_DOMAIN: "kiessla.de"
    LDAP_READONLY_USER: "false"
    LDAP_READONLY_USER_USERNAME: "readonly"
    LDAP_READONLY_USER_PASSWORD: "readonly"
    LDAP_RFC2307BIS_SCHEMA: "false"
    LDAP_BACKEND: "mdb"
    LDAP_TLS: "true"
    LDAP_TLS_CRT_FILENAME: "ldap.crt"
    LDAP_TLS_KEY_FILENAME: "ldap.key"
    LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
    LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
    LDAP_TLS_ENFORCE: "false"
    CONTAINER_LOG_LEVEL: "4"
    LDAP_TLS_REQCERT: "never"
    KEEP_EXISTING_CONFIG: "false"
    LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    LDAP_SSL_HELPER_PREFIX: "ldap"
    LDAP_TLS_VERIFY_CLIENT: "never"
    LDAP_TLS_PROTOCOL_MIN: "3.0"
    LDAP_TLS_CIPHER_SUITE: "NORMAL"

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "1000m"

  ltb-passwd:
    enabled: false

  phpldapadmin:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      path: /
      hosts:
        - "phpldapadmin.caas.i.kiessla.de"
      tls:
      - secretName: "phpldapadmin.acme-tls"
        hosts:
        - "phpldapadmin.caas.i.kiessla.de"
    env:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
