---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secret"
  namespace: {{ .Chart.Name }}
  labels:
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
type: Opaque
data:
  # Admin secrets
  admin.token: {{ .Values.admin.token | b64enc }}

  # SMTP secrets
  smtp.from: {{ .Values.smtp.from | b64enc }}
  smtp.username: {{ .Values.smtp.username | b64enc }}
  smtp.password: {{ .Values.smtp.password | b64enc }}

  # Yubico secrets
  yubico.client-id: {{ .Values.yubico.clientId| b64enc }}
  yubico.secret-key: {{ .Values.yubico.secretKey | b64enc }}
