apiVersion: v2
name: argocd
description: ArgoCD Helm chart as dependency.
type: application
version: 0.1.0
appVersion: v2.2.2
dependencies:
  - name: argo-cd
    version: 3.33.5
    repository: https://argoproj.github.io/argo-helm
