---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: intranet
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - intranet
  peers:
    - intranet
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: internet
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - internet
  peers:
    - internet
