apiVersion: v2
name: jenkins
description: Helm chart for jenkins lts.
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: jenkins
    version: 3.1.13
    repository: https://charts.jenkins.io
