FROM jenkins/jenkins:_version
RUN /usr/local/bin/install-plugins.sh \
    git \
    ldap \
    job-dsl \
    kubernetes \
    role-strategy \
    cloudbees-folder \
    workflow-aggregator \
    pipeline-stage-view \
    github-branch-source \
    configuration-as-code \
