pipeline {
    agent {
        kubernetes {
            inheritFrom 'kaniko'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages {
        stage('Build & Push') {
            steps {
                container('kaniko') {
                    sh '/kaniko/executor -f ./applications/jenkins/Dockerfile --cache=true --destination=tenbriz/jenkins'
                }
            }
        }
    }
}
