jenkins:
  controller:
    # Admin user.
    adminSecret: false

    containerEnv:
      - name: SECRETS
        value: /secrets/jenkins

    installPlugins:
      - git
      - ldap
      - job-dsl
      - kubernetes
      - role-strategy
      - cloudbees-folder
      - workflow-aggregator
      - pipeline-stage-view
      - github-branch-source
      - configuration-as-code

    JCasC:
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.
        ldap-settings: |
          jenkins:
            securityRealm:
              ldap:
                configurations:
                - server: "ldap://openldap.openldap.svc.cluster.local:389"
                  rootDN: "dc=kiessla,dc=de"
                  managerDN: "cn=admin,dc=kiessla,dc=de"
                  managerPasswordSecret: ${LDAP_PASSWORD}
                  userSearchBase: "ou=users"
                  groupSearchBase: "ou=groups"
                  groupSearchFilter: "cn={0}"
                  inhibitInferRootDN: false
                disableMailAddressResolver: false
                disableRolePrefixing: true
                groupIdStrategy: "caseInsensitive"
                userIdStrategy: "caseInsensitive"
        role-strategy-auth: |
          jenkins:
            authorizationStrategy:
              roleBased:
                roles:
                  global:
                    - name: "admin"
                      description: "Jenkins administrators"
                      permissions:
                        - "Overall/Administer"
                      assignments:
                        - "jenkins-admin"
                    - name: "user"
                      description: "Jenkins users"
                      permissions:
                        - "Overall/Read"
                        - "Job/Read"
                      assignments:
                        - "jenkins-user"
        credentials: |
          credentials:
            system:
              domainCredentials:
                - credentials:
                    - usernamePassword:
                        scope: GLOBAL
                        id: "github"
                        username: "realkiessla"
                        password: "${GITHUB_PASSWORD}"
                        description: "Username/Password Credentials for github.com"
                    - usernamePassword:
                        scope: GLOBAL
                        id: "docker"
                        username: "tenbriz"
                        password: "${DOCKER_PASSWORD}"
                        description: "Username/Password Credentials for hub.docker.com"
        jobs: |
          jobs:
            - script: >
                folder('jenkins')

    # Ingress.
    ingress:
      enabled: true
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: "jenkins"
              port:
                number: 8080
      apiVersion: "networking.k8s.io/v1"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostName: "jenkins.caas.i.kiessla.de"
      tls:
        - secretName: "jenkins.acme-tls"
          hosts:
            - "jenkins.caas.i.kiessla.de"

    # Can be used to disable rendering master test resources when using helm template
    testEnabled: false

  agent:
    enabled: true

  additionalAgents:
    kaniko:
      podName: kaniko
      yamlTemplate: |-
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:v1.6.0-debug
            imagePullPolicy: Always
            command:
            - sleep
            args:
            - 99d
            volumeMounts:
              - name: jenkins-docker-cfg
                mountPath: /kaniko/.docker
          volumes:
          - name: jenkins-docker-cfg
            projected:
              sources:
              - secret:
                  name: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json

  persistence:
    volumes:
      - name: jenkins-secrets
        secret:
          secretName: jenkins-secrets
    mounts:
      - name: jenkins-secrets
        mountPath: /secrets/jenkins
        readOnly: true
