apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: i-kiessla-de
  namespace: default
spec:
  secretName: i-kiessla-de-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - '*.i.kiessla.de'
