FROM jenkins/jenkins:lts
RUN jenkins-plugin-cli --plugins \
  git \
  ldap \
  kubernetes \
  role-strategy \
  cloudbees-folder \
  workflow-aggregator \
  pipeline-stage-view \
  github-branch-source \
  configuration-as-code \
