internal:
  controller:
    watchIngressWithoutClass: true
    ingressClassResource:
      name: "nginx"
      enabled: true
      default: true
      controllerValue: "k8s.io/ingress-nginx"
    ingressClass: nginx
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.50.5"

public:
  controller:
    watchIngressWithoutClass: false
    ingressClassResource:
      name: "nginx-public"
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-public"
    ingressClass: nginx-public
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.40.5"
