internal:
  controller:
    watchIngressWithoutClass: true
    ingressClassResource:
      name: "nginx"
      enabled: true
      default: true
      controllerValue: "k8s.io/ingress-nginx"
    ingressClass: nginx
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.50.8" #TODO: Change back before merge!

public:
  controller:
    watchIngressWithoutClass: false
    ingressClassResource:
      name: "nginx-public"
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-public"
    ingressClass: nginx-public
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.40.8" #TODO: Change back before merge!
    config:
      enable-modsecurity: true
      enable-owasp-modsecurity-crs: true
