internal:
  controller:
    watchIngressWithoutClass: true
    ingressClassResource:
      name: "nginx"
      enabled: true
      default: true
      controllerValue: "k8s.io/ingress-nginx"
    ingressClass: nginx
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.50.5"

public:
  controller:
    watchIngressWithoutClass: false
    ingressClassResource:
      name: "nginx-public"
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-public"
    ingressClass: nginx-public
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.40.5"
    config:
      enable-modsecurity: true
      enable-owasp-modsecurity-crs: true

app:
  controller:
    watchIngressWithoutClass: false
    ingressClassResource:
      name: "nginx-app"
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-app"
    ingressClass: nginx-app
    replicaCount: 2
    service:
      loadBalancerIP: "10.0.90.5"
