apiVersion: v2
name: photoprism
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: photoprism
    version: 1.3.1
    repository: https://p80n.github.io/photoprism-helm/
