## Image / POD
image:
  repository: vaultwarden/server
  tag: 1.22.2

## Environment Variables
env:
  ### General Settings
  - name: "DOMAIN"
    value: "https://bitwarden.caas.i.kiessla.de"
  - name: "SIGNUPS_ALLOWED"
    value: "false"
  - name: "INVITATIONS_ALLOWED"
    value: "false"

  ### Admin Settings
  - name: "ADMIN_TOKEN"
    valueFrom:
      secretKeyRef:
        name: "bitwarden-secret"
        key: "admin.token"

  ### SMTP Settings
  - name: "SMTP_HOST"
    value: "posteo.de"
  - name: "SMTP_SSL"
    value: "true"
  - name: "SMTP_EXPLICIT_TLS"
    value: "true"
  - name: "SMTP_FROM"
    valueFrom:
      secretKeyRef:
        name: "bitwarden-secret"
        key: "smtp.from"
  - name: "SMTP_USERNAME"
    valueFrom:
      secretKeyRef:
        name: "bitwarden-secret"
        key: "smtp.username"
  - name: "SMTP_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: "bitwarden-secret"
        key: "smtp.password"

  ### Yubico Settings
  - name: "YUBICO_CLIENT_ID"
    valueFrom:
      secretKeyRef:
        name: "bitwarden-secret"
        key: "yubico.client-id"
  - name: "YUBICO_SECRET_KEY"
    valueFrom:
      secretKeyRef:
        name: "bitwarden-secret"
        key: "yubico.secret-key"

## Resources
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
